NativePHP/nativephp.com

resources/views/docs/navigation.blade.php

Some of the pages are quite long, so needing to scroll all the way up to navigate to another page can be annoying.
With a sticky position it looks like this:

Make navigation sticky

---

resources/views/docs/1/getting-started/installation.md

The minimum required Laravel version is 10, not 9. I tried installing it on a project on 9 and it gives this error:
```Your requirements could not be resolved to an installable set of packages.
Problem 1
- Root composer.json requires nativephp/electron * -> satisfiable by nativephp/electron[0.1.0].
- nativephp/electron 0.1.0 requires illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.15.0] but these were not loaded, likely because it conflicts with another require.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require nativephp/electron:*" to figure out if any version is installable, or "composer require nativephp/electron:^2.1" if you know which you need.
Installation failed, reverting ./composer.json and …
```

Change requirements: minimum Laravel version to 10 and OS to Linux/MacOS

---

resources/views/docs/1/getting-started/configuration.md

The file that is published by the command is called `nativephp.php` not `native.php`

Correct configuration filename

---

resources/views/docs/1/digging-deeper/files.md

👋🏻 
This PR fixes a minor link typo and removes some trailing white space courtesy of my editor.

docs: fix minor typo for fs link

---

resources/views/docs/1/getting-started/introduction.md

I fixed the Tauri website URL because the URL before I fixed it currently redirects to tauri.app.
This is a minor pull request, but it would be a good idea to fix it if there is no particular reason.
Note: My VSCode removed some trailing spaces.

Fix: Tauri website URL

---

resources/views/docs/1/publishing/updating.md

Now that we support GitHub as an updater provider (https://github.com/NativePHP/electron/pull/75), here's the updated docs

docs: add documentation on using GitHub Releases for updates

---

README.md

It was pointing to a file, not the issues tab of the repository

docs: fix link to issues

---

resources/views/docs/1/the-basics/app-lifecycle.md

In this commit: https://github.com/NativePHP/laravel/commit/430fe14e88accad7e0c2c47914e596308d22e178 the default `NativeAppServiceProvider` class is updated. 
In this PR, I've updated the doc accordingly.

Fix: Application Lifecycle doc

---

resources/views/docs/1/the-basics/windows.md

Documentation for:
- https://github.com/NativePHP/laravel/pull/340
- https://github.com/NativePHP/laravel/pull/347
- https://github.com/NativePHP/laravel/pull/349

Docs for v0.5.4

---

resources/views/docs/1/digging-deeper/security.md
resources/views/docs/1/the-basics/system.md

Docs for https://github.com/NativePHP/laravel/pull/357

Safe storage docs

---

resources/views/docs/1/the-basics/power-monitor.md

Happy to reword anything here if you think some concepts could be explained better 👍

Documentation for Power Monitor

---

resources/views/docs/1/publishing/building.md

You cannot create x64 Windows applications on Linux with 64-bit wine. I added that to the documentation. I am using an Ubuntu docker container to build the binaries and needed wine32.
Could this possibly be a bug?

Documented compilation of Windows binaries on Linux

---

resources/views/docs/1/the-basics/screens.md

Base documentation for Screens
I took the part not to repeat the `use` statement in each example.
**Note:** In the first release of NativePHP, I experimented with Screens and wrote some helper functions, like the one I included in the documentation. While digging to write this page, I found some [handy functions](https://www.electronjs.org/docs/latest/api/screen#screengetdisplaymatchingrect) that do the same thing in Electron. Should we implement all those functions?

Docs for Screen facade

---

resources/views/docs/1/the-basics/app-lifecycle.md
resources/views/docs/1/the-basics/application-menu.md
resources/views/docs/1/the-basics/clipboard.md
resources/views/docs/1/the-basics/dialogs.md
resources/views/docs/1/the-basics/menu-bar.md
resources/views/docs/1/the-basics/notifications.md
resources/views/docs/1/the-basics/power-monitor.md
resources/views/docs/1/the-basics/shell.md
resources/views/docs/1/the-basics/system.md
resources/views/docs/1/the-basics/windows.md

I think these kinds of details matter.
Here is my argument for each case:
**Use statement:**  
- Use statements are presented at the beginning of the documentation but not in the subsequent examples, makes it clearer. 
- Each example is copyable and can be directly pasted into your code. If not imported yet, most code editors help the user import the correct class.
**Events:**  
- The same presentation for each "Facade emitting event."  
- At first glance, the user goes through the list of events. Having the name of the event as an h2 allows a user to search for a particular event that they have seen in their logs.
- I’m not trying to transform the documentation into an ApiDoc, I promise.
**Side note:** I don’t think notification events are working. The default event is fired without a …

Proposal: documentation uniformisation 

---

app/Http/Controllers/ShowDocumentationController.php

There is a bug where the generated ToC isn't anchoring to the correct heading when in a code block.
- before: #menubarcontextmenuopened
- now: #codemenubarcontextmenuopenedcode

Fix anchor link on events

---

app/Http/Controllers/ShowDocumentationController.php
resources/views/components/alert-beta.blade.php
resources/views/components/flex-list-of-links.blade.php
resources/views/components/link-button.blade.php
resources/views/components/separator.blade.php
resources/views/docs/index.blade.php
resources/views/docs/navigation.blade.php

Refers to https://github.com/NativePHP/laravel/issues/364
- Add next/previous section buttons to the bottom of pages
- Add Edit on GitHub link to pages

Next, Previous and Edit link

---

resources/views/docs/1/digging-deeper/broadcasting.md

Fix typo in Broadcasting documentation page

---

resources/views/docs/1/digging-deeper/child-process.md

Child Processes

---

resources/js/alpine/codeBlock.js

I have a leading line break in Chrome and Safari. 
Something must have changed on torchlight.dev.
this PR fixes it.

fix: code snippet copy trimmed

---

composer.lock
package-lock.json
package.json

The initial goal was to make it compatible with PHP 8.4 and suppress notices in my local development environment. 
However, I couldn't suppress them all without upgrading to Laravel 11 and Carbon 3.
`herd isolate 8.3` it is for now

chore: update dependencies

---

resources/views/docs/1/the-basics/settings.md

Docs for https://github.com/NativePHP/laravel/pull/432 and https://github.com/NativePHP/electron/pull/141
On less task for: https://github.com/NativePHP/laravel/issues/364
---- 
I understand you prefer not to include Electron-specific details due to the upcoming Tauri driver, but I thought someone might need them for debugging purposes. I added a note indicating that settings are stored in `config.json`, as mentioned in the package documentation [sindresorhus/electron-store](https://github.com/sindresorhus/electron-store).
I also looked for the equivalent package in Tauri, which is [harshkhandeparkar/tauri-settings](https://github.com/harshkhandeparkar/tauri-settings). They replicate everything from tauri-settings but use `settings.json` for the filename, which is configurable.
I believe …

Docs for settings

---

app/Http/Controllers/ShowDocumentationController.php
resources/views/docs/1/getting-started/configuration.md
resources/views/docs/1/getting-started/debugging.md
resources/views/docs/1/getting-started/development.md
resources/views/docs/1/getting-started/env-files.md
resources/views/docs/1/getting-started/installation.md
resources/views/docs/1/getting-started/introduction.md
resources/views/docs/1/getting-started/sponsoring.md
resources/views/docs/1/publishing/building.md
resources/views/docs/1/publishing/publishing.md
resources/views/docs/1/publishing/updating.md
resources/views/docs/1/the-basics/app-lifecycle.md
resources/views/docs/1/the-basics/screens.md
resources/views/docs/1/the-basics/shell.md
resources/views/docs/1/the-basics/system.md
resources/views/docs/index.blade.php

Fixing this report: 
>  I've noticed that the TOC on this page (http://nativephp.com.test/docs/1/the-basics/menu-bar) doesn't show all the headers and I'm not sure why - maybe it's happening on other pages too?

fix: TOC not showing every titles

---

config/torchlight.php

- it takes up horizontal space.  
- doesn't really add value
- you can reactivate it with `// torchlight! {"lineNumbers": false}` if an example really need them

hide line numbers in code block

---

vite.config.js

`npm run dev` stopped working after the fixes for CVE-2025-24010. 
`laravel-vite` has been updated accordingly, but older versions have not been. 
`vite` has updates for versions 4, 5, and 6, while `laravel-vite` has only the latest version. 
This update resolves a CORS issue when using `npm run dev` with `vite >= 4.5.6`.

fix: retrofit laravel-vite changes

---

app/Providers/AppServiceProvider.php
resources/views/components/header-banner.blade.php
resources/views/docs/desktop/1/getting-started/support-policy.md

- Updated AppServiceProvider to share social links to all views
- Implemented new page for desktop docs to provide overview of support policy
This pull request includes several important changes to improve the maintainability and usability of the codebase by centralizing shared view variables and updating documentation. The most significant changes are as follows:
* [`app/Providers/AppServiceProvider.php`](diffhunk://#diff-3f9cb162826c97814fdb7396bf74ebd40cdab174ba6f3e308cbc9a368393e48eR5): Added a new method `registerSharedViewVariables` to centralize the sharing of common view variables such as `discordLink`, `bskyLink`, `openCollectiveLink`, and `githubLink`. The `register` method was updated to call this new method. [[1]](diffhunk://#diff-3f9cb162826c97814fdb7396bf74ebd40cdab174ba6f3e3 …

Implement Support Policy

---

resources/views/docs/desktop/1/publishing/building.md

This pull request adds a new section to the documentation for building applications, specifically detailing how to run commands before and after the build process using hooks in the `config/nativephp.php` file.
Documentation updates:
* [`resources/views/docs/desktop/1/publishing/building.md`](diffhunk://#diff-82c2e00d609526ff9522e83b7b9b7aa8c0461ebaa4e9c464fb6430c6b421e587R28-R46): Added a section on running commands before and after builds, including examples of how to configure the `prebuild` and `postbuild` hooks in the `config/nativephp.php` file.

Provide documentation on pre and postbuild hooks

---

resources/views/docs/desktop/1/the-basics/notifications.md

- Updated the documentation of the Notifications to reflect the changes in https://github.com/NativePHP/laravel/pull/498

Update Notifications docs

---

resources/views/docs/desktop/1/publishing/building.md

I apologise. Looks like my commit to the previous PR to update these commands to legitimate use-cases did not push successfully. (Who knows why, ask the VCS gods)
This change is a very simple one to update the example to one that can be copied and pasted (at least for pre-build)

Update demo commands to legit use cases

---

resources/views/docs/desktop/1/the-basics/alerts.md

Feel free to look over it
PR:
NativePHP/electron: https://github.com/NativePHP/electron/pull/184
NativePHP/laravel: https://github.com/NativePHP/laravel/pull/523

Add documentation for Native Alerts feature

---

resources/views/docs/desktop/1/publishing/publishing.md

While not required, I opted to add the recommended naming convention for GH releases from the electron docs
https://www.electron.build/publish.html#recommended-github-releases-workflow
Note that it does not appear any extra steps are required for the S3 compatible providers, so I've only added GitHub in this PR.
--------
Please let me know if I've missed anything or if you have any thoughts

add GH releases to publishing docs

---

app/Jobs/CreateUserFromStripeCustomer.php
app/Listeners/StripeWebhookReceivedListener.php
app/Providers/AppServiceProvider.php

- Sends failing jobs to sentry
- Improves handling & timing of new stripe customers by also attempting to create a user record for `customer.subscription.created` when a matching user is missing.

Improve stripe handling

---

app/Jobs/CreateAnystackLicenseJob.php
app/Jobs/CreateUserFromStripeCustomer.php
app/Jobs/HandleCustomerSubscriptionCreatedJob.php
database/migrations/2025_05_10_012033_add_anystack_contact_id_to_users_table.php
tests/Feature/Jobs/CreateAnystackLicenseJobTest.php
tests/Feature/Jobs/CreateUserFromStripeCustomerTest.php
tests/Feature/Jobs/HandleCustomerSubscriptionCreatedJobTest.php
tests/Feature/Livewire/OrderSuccessTest.php
tests/Feature/StripePurchaseHandlingTest.php

This should be g2g. Going to merge tomorrow when I can be available for triage.

Store anystack contact ids on users table

---

.github/workflows/tests.yaml
composer.json
composer.lock
phpunit.xml

The new `.github/workflows/tests.yaml` workflow supports unit and feature tests, using Composer dependency caching and an in-memory SQLite database. It compiles assets and generates an application key before test execution.
The `composer.json` now includes `doctrine/dbal` (version `^3.9`) because otherwise it would not migrate on my machine.

feat: configure tests workflow

---

app/Jobs/CreateAnystackLicenseJob.php
app/Listeners/StripeWebhookReceivedListener.php
tests/Feature/StripePurchaseHandlingTest.php

Removes the `customer.created` webhook trigger.
Intended to reduce failures from someone attempting a purchase, the charge failing (but stripe still creating a customer, which means we still made a user), and then succeeding with a secondary+ purchase (resulting in conflicting stripe customers).

Only create a new user upon customer.subscription.created webhook

---

resources/views/docs/desktop/1/digging-deeper/broadcasting.md

This PR fixes a typo in the documentation, changing "JavaSscript" to the correct spelling "JavaScript".

Fix typo in Broadcasting documentation ("JavaSscript" → "JavaScript")

---

app/Livewire/MobilePricing.php
app/Livewire/PurchaseModal.php
resources/views/early-adopter.blade.php
resources/views/livewire/mobile-pricing.blade.php
resources/views/livewire/purchase-modal.blade.php
tests/Feature/Livewire/PurchaseModalTest.php
tests/Feature/MobilePricingTest.php
tests/Feature/MobileRouteTest.php

- When a guest visits the `/mobile` route (everyone, before auth is in place) and clicks one of the buttons to purchase a license, we'll now show them a modal to collect their email.
- Upon submitting the email, we'll determine if a user already exists for that email. If one does not, we create one with the supplied email. Then, we create a stripe customer record for the user record if necessary and then redirect to a customer-specific checkout session in Stripe for the correct plan.
- Once a purchase is completed, we do the regular work:
- Cashier handles subscription info for the existing user record.
- We create an anystack contact (if necessary) and create a license.
This has been coded to also handle an authenticated user visiting the `/mobile` page. When this happens, we do not show …

V2 purchase flow

---

resources/views/early-adopter.blade.php
resources/views/livewire/mobile-pricing.blade.php
resources/views/partners.blade.php
routes/web.php

Partners page

---

app/Jobs/HandleCustomerSubscriptionCreatedJob.php

Reverts NativePHP/nativephp.com#147
Turns out this doesn't work, as all subscriptions are incomplete at the time of creation.

Revert "Do not create a license upon inactive subscription creation"

---

app/Exceptions/InvalidStateException.php
app/Jobs/HandleInvoicePaidJob.php
app/Listeners/StripeWebhookHandledListener.php
app/Listeners/StripeWebhookReceivedListener.php
tests/Feature/StripePurchaseHandlingTest.php

Added `invoice.paid` to our production webhook events on Stripe.
I tested this locally for:
- a new user performs a checkout and pays successfully (license created)
- a new user performs a checkout, payment fails, and then payment succeeds (license created)
- a user performs a checkout, payment fails, and then they use the billing portal to pay the invoice at a slightly later time (license created)
- an existing user that doesn't already exist on stripe yet already has a license (old anystack contacts) performs a checkout and pays (new license created)
I can still think of some edge cases this won't handle. I will get going on those as soon as I can.
Also... definitely some refactoring that needs to be done to clean this all up once we've hit a steady state and our logic stops changing. …

Create a license upon invoice.paid event

---

resources/views/docs/desktop/1/getting-started/development.md

Updated the documentation to include `public/icon.ico` for Windows and `public/icon.icns` for macOS as optional icon files. This clarifies how these files are utilized when building desktop applications.
NativePHP/electron PR: https://github.com/NativePHP/electron/pull/216

Add optional icon file support for Windows and macOS

---

resources/views/docs/desktop/1/the-basics/settings.md

Docs Update for https://github.com/NativePHP/laravel/pull/562
This pull request updates the documentation for the `Settings::get` method to clarify the use of default values and provide an example of using a closure as a default.
Documentation updates:
* [`resources/views/docs/desktop/1/the-basics/settings.md`](diffhunk://#diff-bd2d9d896efb265349d39ac862c141461ce0e71c2f7cb625d3d65b86e8ea2481L30-R39): Enhanced the explanation of the `Settings::get` method to include the option of providing a closure as a default value. Added an example demonstrating how to use a closure and clarified the behavior when no default value is provided (returns `null`).

Add documentation for new closure support

---

resources/views/components/eap-banner.blade.php

Changes the eap banner to calculate the countdown based on UTC rather than the user's/browser's timezone.

Calculate countdown from UTC

---

resources/views/early-adopter.blade.php

Simple fix to remove a reference to the EAP that slipped through the cracks.
Hmm. Looks like we have some formatting inconsistencies between devs showing up in this PR. Will need to look into that at some point.

Remove missed reference of the EAP

---

resources/views/components/navigation-bar.blade.php

When viewing the NativePHP website on a mobile device, it is difficult for users to navigate to the mobile page to purchase a licence directly form the home page.
This PR ensures the mobile navigation item is present on mobile devices - as currently the user meeds to navigate to the docs, then go to installation page and then select to obtain a licence.

Show the mobile navigation on mobile

---

resources/views/welcome.blade.php

Don't mind the formatting changes..
Only important change is the mobile CTA button now has an href of `/mobile` instead of the docs.

Homepage mobile cta button routes to /mobile

---

resources/views/docs/desktop/1/the-basics/application-menu.md

Described how to use the `Native.contextMenu()` method to define a custom native context menu in the Application Menu page of the documentation.

Add documentation for context menu

---

resources/views/docs/desktop/1/the-basics/system.md

Docs for https://github.com/NativePHP/electron/pull/229
I kept this around, but it seems to be accomplishing the same thing

Add printer settings

---

resources/views/components/layout.blade.php

The <title> tag is now only rendered if the SEO meta title is the default or empty, preventing duplicate title.

Fix: Prevent duplicate <title> tags by conditionally rendering manual title in layout

---

composer.json
composer.lock

Updates Livewire to v3.6.4 for CVE.
Updated composer.json just to be explicit in the change.

Update livewire to 3.6.4

---

app/Http/Controllers/Api/LicenseController.php
app/Http/Resources/Api/LicenseResource.php
routes/api.php
tests/Feature/Api/CreateLicenseTest.php
tests/Feature/Api/GetLicenseTest.php

Needed on [bifrost.nativephp.com](https://bifrost.nativephp.com)

feat: add API endpoint to retrieve license details by key

---

app/Http/Controllers/ShowDocumentationController.php
resources/js/alpine/copyMarkdown.js
resources/js/app.js
resources/views/components/docs/copy-markdown-button.blade.php
resources/views/components/docs/toc-and-sponsors.blade.php
resources/views/components/icons/copy.blade.php
resources/views/docs/index.blade.php
routes/web.php

This PR adds raw markdown file access via .md URLs so user can access raw markdown by add .md in the end of any documentation page (similar to Laravel's official docs). It also adds a "Copy as Markdown" button on all documentation pages to easily copy the opened documentation page as markdown.

Feature: Markdown Viewer and Copy-to-Clipboard for Docs

---

resources/views/docs/desktop/1/the-basics/application.md

**This PR allows developers to obtain localisation information of the application and the system via the `App` facade.**
It adds three new methods to the facade that are proxies for the Electron methods `app.getLocale()`, `app.getLocaleCountryCode()`, and `app.getSystemLocale()` (see details on the [Electron documentation](https://www.electronjs.org/docs/latest/api/app#appgetlocale)). This allows developers to improve the localisation of their application, e.g. by automatically setting or suggesting a language that matches the system language when a NativePHP application is first launched.
_Electron PR:_ https://github.com/NativePHP/electron/pull/247
_Laravel PR:_ https://github.com/NativePHP/laravel/pull/681
If there's anything you'd like me to tweak or improve in this PR, please let me …

Add documentation for new locale information methods

---

resources/views/docs/desktop/1/the-basics/windows.md

This PR adds some documentation for restricting the navigation options of a window.
See https://github.com/NativePHP/laravel/pull/686 for further details.

Add documentation for window navigation restriction
