NativePHP/nativephp.com

resources/views/docs/1/the-basics/dialogs.md

I noticed there was an undocumented method for opening folders.

Document opening folders with the native dialog

---

resources/views/docs/1/the-basics/windows.md

Documentation for the open pull requests on the main project.

Document hideMenu

---

resources/views/docs/1/getting-started/installation.md

Documentation is not very clear NativePHP is a Laravel package. For beginners, instructions as is might be a bit misleading. 
Make it explicit that an existing Laravel app is needed.

Update installation.md to make it explicit a Laravel app is needed

---

resources/views/docs/1/the-basics/menu-bar.md

This PR adds nice screenshots to the `Menu Bar` documentation.

Adding images to menu bar docs

---

resources/views/docs/1/the-basics/app-lifecycle.md

Related: https://github.com/NativePHP/laravel/pull/98

Add `Customize php.ini With Provider`

---

resources/views/docs/1/publishing/updating.md

Including the link to the Learn AWS post on how to correctly configure the AWS S3 bucket.

Including Learn AWS Link

---

resources/views/docs/1/publishing/building.md
yarn.lock

I had an issue, and noted in Discord others having this issue, of not doing this then having issues with migrations not running.

Update docs to explain version update needed to trigger migrations in app update

---

resources/views/docs/1/digging-deeper/child-processes.md

To go with https://github.com/NativePHP/electron/pull/123
If https://github.com/NativePHP/laravel/pull/402 passes too, I will add a sentence before merging this PR.

Updated child-processes.md 

---

resources/views/docs/1/digging-deeper/broadcasting.md

This PR updates the Livewire examples in the Broadcasting docs in relation to [this issue](https://github.com/NativePHP/laravel/issues/449)

Update the Livewire examples in the broadcasting docs

---

app/Http/Controllers/ShowDocumentationController.php
config/seotools.php

At the end of a section, previously the "next" button would not display the first page of the next section.
Fixed.

fix: jump to next section

---

composer.lock
package-lock.json
resources/views/components/header-banner.blade.php

fix doc search not showing on Safari iOS

fix: mobile doc search

---

resources/views/docs/1/publishing/building.md

I added a paragraph about Mac notarization being required I you want to run your app on other machines.
As noted in this PR https://github.com/NativePHP/laravel/issues/466

add note about mac notarization

---

resources/views/docs/1/digging-deeper/files.md

This PR adds some recommendations about the usage of symlinks. 
@simonhamp You mentioned this some time ago in discord. Feel free to make changes!

add section about symbolic links

---

resources/views/docs/desktop/1/getting-started/introduction.md

- Added a link to https://github.com/NativePHP/awesome-nativephp

Include link to awesome-nativephp repo

---

resources/views/docs/desktop/1/getting-started/installation.md

See for context: https://github.com/orgs/NativePHP/discussions/506

Include note to update `minimum-stability` to "dev"

---

resources/views/docs/desktop/1/getting-started/support-policy.md

Here https://nativephp.com/docs/desktop/1/getting-started/support-policy#laravel-versions On Line 28, Is It Supported PHP Versions or Supported Laravel Versions?

On Line 28, Is It Supported PHP Versions or Supported Laravel Versions?

---

resources/views/docs/desktop/1/the-basics/app.md
resources/views/docs/desktop/1/the-basics/application.md

Add documentation for App facade

---

resources/views/early-adopter.blade.php

Fixes typo

---

resources/views/docs/desktop/1/digging-deeper/security.md

Updated the docs to reflect the changes in [PR551](https://github.com/NativePHP/laravel/pull/551)

update `PreventRegularBrowserAccess` middleware docs

---

app/Livewire/OrderSuccess.php
tests/Feature/Livewire/OrderSuccessTest.php

Just some logic clean up now that we're working with a different data setup vs. v1.
Basically, we now retrieve the checkout session, inspect the subscription associated with it, query the db for that subscription, its item, and the item's license. From there, we can resolve the related email, license key, and subscription plan.

Refactor order success page logic
